name = "bps-order-portal"
compatibility_date = "2026-07-15"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "bps-order-portal"
database_id = "fa68bf94-f2fb-4f22-946e-eec21b3ed5d4"

[[r2_buckets]]
binding = "ORDER_FILES"
bucket_name = "bps-order-files"

[observability]
enabled = true
